name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        if: always()
      - run: docker build . --file Dockerfile -t plimage
        continue-on-error: true
      - run: docker run -d --name plcontainer plimage
      - run: sudo docker cp plcontainer:./tests/allure-results allure-results
      - uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
      - uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: allure-history
